import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const unitsPath = join(root, 'data/units.json');
const factionsPath = join(root, 'data/factions.json');
const abilitiesPath = join(root, 'data/abilities.json');
const schemaPath = join(root, 'schemas/units/units.schema.json');
const outputPath = join(root, 'packages/core/src/generated/units.ts');

const ajvPath = join(
  root,
  'node_modules/.pnpm/@redocly+ajv@8.11.2/node_modules/@redocly/ajv/dist/2020.js',
);
const { default: Ajv } = await import(pathToFileURL(ajvPath).href);

const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
const ajv = new Ajv({ allErrors: true, strict: false });
const validate = ajv.compile(schema);

const units = JSON.parse(readFileSync(unitsPath, 'utf8'));
if (!Array.isArray(units)) {
  throw new Error(`${unitsPath} must be a JSON array of unit definitions`);
}

if (!validate(units)) {
  const details = validate.errors?.map((error) => `${error.instancePath} ${error.message}`).join('; ');
  throw new Error(`Invalid unit catalog: ${details}`);
}

const ids = new Set(units.map((unit) => unit.id));
if (ids.size !== units.length) {
  throw new Error(`Duplicate unit ids in ${unitsPath}`);
}

if (units.length === 0) {
  throw new Error(`No units defined in ${unitsPath}`);
}

const factions = JSON.parse(readFileSync(factionsPath, 'utf8'));
const factionIds = new Set(factions.map((faction) => faction.id));
const abilities = JSON.parse(readFileSync(abilitiesPath, 'utf8'));
const abilityIds = new Set(abilities.map((ability) => ability.id));
for (const unit of units) {
  if (!factionIds.has(unit.factionId)) {
    throw new Error(`Unit ${unit.id} references unknown factionId: ${unit.factionId}`);
  }
  if (!abilityIds.has(unit.abilityId)) {
    throw new Error(`Unit ${unit.id} references unknown abilityId: ${unit.abilityId}`);
  }
}

const serialized = JSON.stringify(units, null, 2);
const output = `/* eslint-disable */
/** Generated by scripts/compile-units.mjs — do not edit. */
import type { AttackType, MovementType } from '../types/combat-enums.js';

export const UNITS = ${serialized} as const;

export type UnitType = (typeof UNITS)[number]['id'];

export type Unit = (typeof UNITS)[number];

export const UNIT_CATALOG: Record<UnitType, Unit> = Object.fromEntries(
  UNITS.map((unit) => [unit.id, unit]),
) as Record<UnitType, Unit>;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output, 'utf8');
console.log(`Compiled ${units.length} units from ${unitsPath} to ${outputPath}`);
